---
title: "R Notebook"
output:
  github_document: default
---


```{r}
library(tidyverse)
library(magick)
library(igraph)
library(png)
library(gganimate)
```

```{r}
# img <- image_read("olin_o.jpg")
# img
```

```{r}
# Load the Olin logo
img <- image_read("olin.jpg")
radius <- 0 # default 0
sigma <- 1 # default 1
lower_pct <- 10 # default 10
upper_pct <- 30 # default 30
geom_string <- paste(
  radius,
  "x",
  sigma,
  "+",
  lower_pct,
  "%+",
  upper_pct,
  ""
)

edges_img <- img %>%
  # image_enhance() #%>%
  # image_normalize() #%>%
  image_scale(500) %>% # default 500
  image_canny(geometry = geom_string)
  # image_quantize(max = 2, colorspace = "gray", dither = FALSE) %>%
  # image_negate()
edges_img
```

```{r}
# Load the rickroll
# img <- image_read("rick.jpg")
# radius <- 0 # default 0
# sigma <- 1 # default 1
# lower_pct <- 3 # default 10
# upper_pct <- 12 # default 30
# geom_string <- paste(
#   radius,
#   "x",
#   sigma,
#   "+",
#   lower_pct,
#   "%+",
#   upper_pct,
#   ""
# )
# 
# edges_img <- img %>% 
#   # image_enhance() #%>%
#   # image_normalize() #%>%
#   image_scale(500) %>% # default 500
#   image_canny(geometry = geom_string)
#   # image_quantize(max = 2, colorspace = "gray", dither = FALSE) %>%
#   # image_negate()
# edges_img
```



```{r}
# spit out the image to a png and then re-import it into a dataframe
# This is kinda roundabout but whatever
img_df <- edges_img %>%
  image_write(tempfile(fileext='png'), format = 'png') %>%
  readPNG() %>%
  as.data.frame()
```

```{r}
ones <- data.frame(x = integer(), y = integer())
for(i in 1:nrow(img_df)){ # For each row and column in the image dataframe
  for(j in 1:ncol(img_df)){
    if(img_df[i,j] == 1){ # if the pixel at this location is 1
      # print(x[i,j])
      new <- data.frame(r = i, c = j) # make a dataframe with this location
      ones <- rbind(ones,new) # bind the new dataframe to the existing one
      # basically add a row to it
    }
  }
}
```


```{r}
# Remove L shapes of pixels

for(i in 1:nrow(ones)){ # For each row and column in the image dataframe
  if( # If this pixel isn't on the edge of the image
    # Technically it should check each neighbor but whatever
      ones[i,1] >= 2 & 
      ones[i,1] <= nrow(img_df) - 1 & 
      ones[i,2] >= 2 & 
      ones[i,2] <= ncol(img_df) - 1
  ){
    r <- ones[i,1] # get this pixel's row and column
    c <- ones[i,2]
    up <- img_df[r-1,c] == 1 #Booleans for if each non-diagonal neighbor is white
    left <- img_df[r,c-1] == 1
    down <- img_df[r+1,c] == 1
    right <- img_df[r,c+1] == 1
    if( # If L-shaped
      (up & left & !down) |
      (up & right & !down) |
      (down & left & !up) |
      (down & right & !up) |
      (up + left + right + down > 2)
    ){
      img_df[r,c] = 0 # then my value needs to be zero
      # ones <- ones %>%
      #   filter(r != r, c != c)
    }
  }
}

# We have to recalculate ones again. The L-remover would get more complicated
# if I removed ones from the ones dataframe as it ran
ones <- data.frame(x = integer(), y = integer())
for(i in 1:nrow(img_df)){ # For each row and column in the image dataframe
  for(j in 1:ncol(img_df)){
    if(img_df[i,j] == 1){ # if the pixel at this location is 1
      # print(x[i,j])
      new <- data.frame(r = i, c = j) # make a dataframe with this location
      ones <- rbind(ones,new) # bind the new dataframe to the existing one
      # basically add a row to it
    }
  }
}
```

```{r}

# all neighbors
# -1,-1
# -1,0
# -1,1
# 0,-1
# 0,1
# 1,-1
# 1,0
# 1,1
# neighborrs <- c(-1,-1,-1,0,0,1,1,1)
# neighborcs <- c(-1,0,1,-1,1,-1,0,1)

# only next neighbors (reading order)
# 0,1
# 1,-1
# 1,0
# 1,1

# Create a dataframe of relative neighbor positions. Because everything iterates
# over rows and columns going from 0 to max, we only need to check neighboring 
# pixels that are to the right or below the current pixel

neighborrs <- c(0,1,1,1) # make these positions as lists
neighborcs <- c(1,-1,0,1)


# neighborrs <- c(0,1) # version that ignores diagonals
# neighborcs <- c(1,0)

# neighborrs <- c(1,1) # only use diagonals
# neighborcs <- c(-1,1)


nbrs <- data.frame(
  r = neighborrs,
  c = neighborcs
) # make a dataframe from the lists

edges <- data.frame(
  x1 = integer(),
  y1 = integer(),
  x2 = integer(),
  y2 = integer()
) # create an empty dataframe for each edge

for(a in 1:nrow(ones)){ # for each pixel of value one
  my_pos <- ones[a,]
  my_posr <- my_pos[1,1] # get the row and column of that pixel
  my_posc <- my_pos[1,2]
  for(b in 1:nrow(nbrs)){ # for each neighbor pixel
    nbr_posr_rel <- nbrs[b,1] # get the relative row and column
    nbr_posc_rel <- nbrs[b,2]
    nbr_posr <- my_posr + nbr_posr_rel #calculate the absolute row and column
    nbr_posc <- my_posc + nbr_posc_rel
    if(
      nbr_posr >= 1 & 
      nbr_posr <= nrow(img_df) & 
      nbr_posc >= 1 & 
      nbr_posc <= ncol(img_df)
    ){ # if the neighbor pixel is within the bounds of the image
      if(img_df[nbr_posr,nbr_posc] == 1){ # if the neighbor pixel is 1
        edge <- data.frame( # create a 1 row dataframe with the pixel value
          x1 = my_posc, 
          y1 = my_posr,
          x2 = nbr_posc,
          y2 = nbr_posr
        )
        edges <- rbind(edges,edge) # add that row to the edges dataframe
      }
    }
  }
}

```


```{r}
edges %>%
  mutate(y1 = -y1, y2 = -y2) %>%
  ggplot(aes(x = x1, y = y1, xend = x2, yend = y2)) +
  geom_segment(lineend = "square") +
  coord_fixed()
```


```{r}
# robot instruction generator

posx <- edges[1,1]
posy <- edges[1,2]
queue <- edges
instructions <- c(paste("GO", sprintf("%03d", posx), sprintf("%03d", posy), sep = ",")) # go to the first point
instructions <- c(instructions, "DN........")
while(nrow(queue) > 0){ # while there are still edges in the queue
  df <- queue %>% # check for queued edges to draw that connect to my current point
    filter((x1 == posx & y1 == posy) | (x2 == posx & y2 == posy))
  if(nrow(df) == 0){ # If there are no queued edges,then go to the start of the
    # next edge in the queue
    instructions <- c(instructions, "UP........")
    posx <- queue[1,1]
    posy <- queue[1,2]
    instructions <- c(instructions, paste("GO", sprintf("%03d", posx), sprintf("%03d", posy), sep = ","))
    instructions <- c(instructions, "DN........")
  } else { # If there are queued edges
    next_edge <- df[1,]
    if(posx == next_edge[1,1] & posy == next_edge[1,2]){ # Find the next point
      # to travel to
      new_posx <- next_edge[1,3]
      new_posy <- next_edge[1,4]
    } else {
      new_posx <- next_edge[1,1]
      new_posy <- next_edge[1,2]
    }
    #Drive to that point
    instructions <- c(instructions, paste("GO", sprintf("%03d", new_posx), sprintf("%03d", new_posy), sep = ","))
    queue <- queue %>% #Remove the edge we just traveled from the queue
      filter(!((x1 == posx & y1 == posy & x2 == new_posx & y2 == new_posy)|
               (x2 == posx & y2 == posy & x1 == new_posx & y1 == new_posy)))
    posx <- new_posx # Current position is now the next position
    posy <- new_posy
  }
}



```

```{r}
# Check number of movement segments for testing
instructions %>%
  as.data.frame %>%
  filter(. != "DN" & . != "UP")
```



```{r}
# All the same instruction generator except this only tracks the xy positions.
# See above for comments

posx <- edges[1,1]
posy <- edges[1,2]
queue <- edges
# foo <- edges %>% filter((x1 == posx & y1 == posy) | (x2 == posx & y2 == posy))
# instructions <- c(paste(posx, posy, sep = ","))
instructions_x <- c()
instructions_y <- c()
while(nrow(queue) > 0){
# for(i in 1:200){
  df <- queue %>%
    filter((x1 == posx & y1 == posy) | (x2 == posx & y2 == posy))
    # filter(x1 == posx & y1 == posy)
  if(nrow(df) == 0){
    posx <- queue[1,1]
    posy <- queue[1,2]
    # instructions <- c(instructions, paste(posx, posy, sep = ","))
    instructions_x <- c(instructions_x, posx)
    instructions_y <- c(instructions_y, posy)
  } else {
    next_edge <- df[1,]
    if(posx == next_edge[1,1] & posy == next_edge[1,2]){
      new_posx <- next_edge[1,3]
      new_posy <- next_edge[1,4]
    } else {
      new_posx <- next_edge[1,1]
      new_posy <- next_edge[1,2]
    }
    # instructions <- c(instructions, paste(new_posx, new_posy, sep = ","))
    instructions_x <- c(instructions_x, new_posx)
    instructions_y <- c(instructions_y, new_posy)
    queue <- queue %>%
      filter(!((x1 == posx & y1 == posy & x2 == new_posx & y2 == new_posy)|
               (x2 == posx & y2 == posy & x1 == new_posx & y1 == new_posy)))
    # queue <- queue %>%
    #   filter(x1 != next_edge[1,1] & y1 != next_edge[1,2] & x2 != next_edge[1,3] & y2 != next_edge[1,4])
    posx <- new_posx
    posy <- new_posy
  }
}
instructions_pos <- data.frame(
  x = instructions_x,
  y = instructions_y
)
```

```{r}
# Draw every segment that the robot moves, whether or not the line is being drawn

instructions_pos %>%
  mutate(yprev = lag(y), xprev = lag(x)) %>%
  mutate(y = -y, yprev = -yprev) %>%
  ggplot(aes(x = x, y = y, xend = xprev, yend = yprev)) +
  geom_segment(lineend = "square") +
  coord_fixed()
```

```{r}
# Do all of the same things as above but with functions in a separate file
source("generate_fns.R")

img_df <- generate_matrix(edges_img)
edges <- generate_edges(img_df)
instructions <- generate_instructions(edges)
instructions
```
```{r}
write(instructions, "test.txt")
```

```{r}
instructions %>%
    mutate(
      x = x %>% as.character(),
      y = y %>% as.character()
    )
```


